<a href="https://colab.research.google.com/github/jayanth940/Jayanth/blob/main/Numpy_25_May.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### Manual Creation of the Arrays

In [ ]:
list1 = [10,20,30,40,50,60,70]

In [ ]:
print(list1)

[10, 20, 30, 40, 50, 60, 70]


In [ ]:
list1 * 2

[10, 20, 30, 40, 50, 60, 70, 10, 20, 30, 40, 50, 60, 70]

In [ ]:
twice = []

for val in list1:
    twice.append(val * 2)

In [ ]:
twice

[20, 40, 60, 80, 100, 120, 140]

In [ ]:
arr1 = np.array(list1)

In [ ]:
print(arr1)

[10 20 30 40 50 60 70]


In [ ]:
print(arr1 * 2)

[ 20  40  60  80 100 120 140]


In [ ]:
list(arr1)
tuple(list1)
set(arr1)

### Using functions to create Arrays

- np.arange
- np.ones
- np.zeros
- np.full
- np.linspace
- np.random.random
- np.random.randint
- np.diag
- np.eye

#### np.arange function

In [ ]:
np.arange(100000000)

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

In [ ]:
np.arange(1, 11)  #(start_value, stop_value+1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1.0, 11.0)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.arange(10, 101, 5) #(start_value, stop_value+1, step_value)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

#### **reshaping the arange function into 2d array**

In [ ]:
np.arange(24).reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### np.ones function

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((5,5)) * 25

array([[25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.],
       [25., 25., 25., 25., 25.]])

#### np.zeros function

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((8,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### np.full function

In [ ]:
np.full(10, 25)

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [ ]:
np.full((12, 10), 15)

array([[15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15, 15, 15, 15, 15, 15]])

#### np.eye function

In [ ]:
np.eye(5) * 10

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0., 10.]])

#### np.diag function

In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### np.random.random function

In [ ]:
np.random.random(5) #random array of random float values between 0 and 1

array([0.603447  , 0.00876399, 0.36469841, 0.98688675, 0.94051809])

In [ ]:
np.random.random((5,5))

array([[0.79727502, 0.8189231 , 0.95577852, 0.56575228, 0.18021661],
       [0.75430326, 0.96259932, 0.7484443 , 0.63483656, 0.28774232],
       [0.65438567, 0.28091727, 0.0428501 , 0.99088435, 0.48615892],
       [0.68804397, 0.07512012, 0.64399107, 0.28042079, 0.28605076],
       [0.39643007, 0.50206962, 0.91395347, 0.44512616, 0.83140549]])

#### np.random.randint function

In [ ]:
np.random.randint(10, size = 5)

array([7, 0, 3, 9, 4])

In [ ]:
np.random.randint(10, 50, size = 5)

array([14, 10, 41, 11, 48])

In [ ]:
np.random.randint(10, 50, size = (5,4))

array([[32, 26, 20, 32],
       [17, 28, 26, 49],
       [47, 35, 26, 10],
       [46, 29, 46, 31],
       [20, 42, 27, 20]])

#### **np.linspace(linearly spaced values) function**

In [ ]:
np.linspace(1, 50, 9)

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [ ]:
np.linspace(0,1,10000)

array([0.00000000e+00, 1.00010001e-04, 2.00020002e-04, ...,
       9.99799980e-01, 9.99899990e-01, 1.00000000e+00])

## **Indexing and Slicing**

In [ ]:
arr1 = np.arange(10,91,10).reshape(3,3)

In [ ]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr1[1,2]

np.int64(60)

In [ ]:
arr1[1]

array([40, 50, 60])

In [ ]:
arr1[:, 1]

array([20, 50, 80])

In [ ]:
arr1[:, 1:3]

array([[20, 30],
       [50, 60],
       [80, 90]])

#### **numpy where function**

In [ ]:
arr1 > 40

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr1[arr1 > 40]

array([50, 60, 70, 80, 90])

In [ ]:
arr1[(arr1 >= 20) & (arr1 <= 80)]

array([20, 30, 40, 50, 60, 70, 80])

In [ ]:
arr1[(arr1 >= 20) | (arr1 <= 80)]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
i = np.where(arr1 > 40)

In [ ]:
arr1[i]

array([50, 60, 70, 80, 90])

## **Array Mathematics**

- Simple mathematical operations(Today)
- Complex linear algebra based mathematical operations(later)

In [ ]:
arr3 = np.random.randint(10, 31, size = (3,3))
arr4 = np.random.randint(40, 81, size = (3,3))

In [ ]:
arr3

array([[10, 29, 21],
       [14, 18, 17],
       [20, 27, 12]])

In [ ]:
arr4

array([[69, 75, 79],
       [46, 46, 76],
       [65, 73, 71]])

In [ ]:
arr3 + arr4

array([[ 79, 104, 100],
       [ 60,  64,  93],
       [ 85, 100,  83]])

In [ ]:
np.add(arr3, arr4)

array([[ 79, 104, 100],
       [ 60,  64,  93],
       [ 85, 100,  83]])

In [ ]:
arr3 / 10

array([[1. , 2.9, 2.1],
       [1.4, 1.8, 1.7],
       [2. , 2.7, 1.2]])

In [ ]:
arr3 - arr4

array([[-59, -46, -58],
       [-32, -28, -59],
       [-45, -46, -59]])

In [ ]:
arr4 - arr3

array([[59, 46, 58],
       [32, 28, 59],
       [45, 46, 59]])

In [ ]:
arr3 * arr4

array([[ 690, 2175, 1659],
       [ 644,  828, 1292],
       [1300, 1971,  852]])

In [ ]:
arr3 / arr4

array([[0.14492754, 0.38666667, 0.26582278],
       [0.30434783, 0.39130435, 0.22368421],
       [0.30769231, 0.36986301, 0.16901408]])

### Mean, Sum, Min, Max, Median of the Arrays

In [ ]:
arr = np.random.randint(50, 91, size = (10,8))

In [ ]:
arr

array([[89, 60, 64, 59, 58, 62, 86, 82],
       [52, 64, 66, 70, 64, 76, 52, 89],
       [51, 65, 74, 67, 67, 80, 53, 68],
       [59, 78, 68, 64, 71, 52, 50, 59],
       [79, 73, 65, 73, 74, 57, 78, 52],
       [54, 66, 80, 52, 73, 87, 58, 85],
       [65, 85, 77, 87, 61, 68, 82, 84],
       [62, 74, 72, 57, 65, 63, 85, 90],
       [70, 81, 62, 69, 52, 55, 70, 86],
       [64, 68, 60, 87, 84, 88, 89, 72]])

In [ ]:
np.mean(arr)

np.float64(69.4875)

In [ ]:
np.mean(arr, axis = 0)  #axis = 0 means column-wise

array([64.5, 71.4, 68.8, 68.5, 66.9, 68.8, 70.3, 76.7])

In [ ]:
np.mean(arr, axis = 1)  #axis = 1 means row-wise

array([70.   , 66.625, 65.625, 62.625, 68.875, 69.375, 76.125, 71.   ,
       68.125, 76.5  ])

In [ ]:
np.median(arr)

np.float64(68.0)

In [ ]:
np.median(arr, axis = 0)

array([63. , 70.5, 67. , 68. , 66. , 65.5, 74. , 83. ])

In [ ]:
np.median(arr, axis = 1)

array([63. , 65. , 67. , 61.5, 73. , 69.5, 79.5, 68.5, 69.5, 78. ])

In [ ]:
np.min(arr)

np.int64(50)

In [ ]:
np.min(arr, axis = 0)

array([51, 60, 60, 52, 52, 52, 50, 52])

In [ ]:
np.min(arr, axis = 1)

array([58, 52, 51, 50, 52, 52, 61, 57, 52, 60])

In [ ]:
np.max(arr)

np.int64(90)

In [ ]:
np.max(arr, axis = 0)

array([89, 85, 80, 87, 84, 88, 89, 90])

In [ ]:
np.max(arr, axis = 1)

array([89, 89, 80, 78, 79, 87, 87, 90, 86, 89])

In [ ]:
np.sum(arr)

np.int64(5559)

In [ ]:
np.sum(arr, axis = 0)

array([645, 714, 688, 685, 669, 688, 703, 767])

In [ ]:
np.sum(arr, axis = 1)

array([560, 533, 525, 501, 551, 555, 609, 568, 545, 612])

### Sorting the Arrays

In [ ]:
arr

array([[89, 60, 64, 59, 58, 62, 86, 82],
       [52, 64, 66, 70, 64, 76, 52, 89],
       [51, 65, 74, 67, 67, 80, 53, 68],
       [59, 78, 68, 64, 71, 52, 50, 59],
       [79, 73, 65, 73, 74, 57, 78, 52],
       [54, 66, 80, 52, 73, 87, 58, 85],
       [65, 85, 77, 87, 61, 68, 82, 84],
       [62, 74, 72, 57, 65, 63, 85, 90],
       [70, 81, 62, 69, 52, 55, 70, 86],
       [64, 68, 60, 87, 84, 88, 89, 72]])

In [ ]:
np.sort(arr, axis = 0)

array([[51, 60, 60, 52, 52, 52, 50, 52],
       [52, 64, 62, 57, 58, 55, 52, 59],
       [54, 65, 64, 59, 61, 57, 53, 68],
       [59, 66, 65, 64, 64, 62, 58, 72],
       [62, 68, 66, 67, 65, 63, 70, 82],
       [64, 73, 68, 69, 67, 68, 78, 84],
       [65, 74, 72, 70, 71, 76, 82, 85],
       [70, 78, 74, 73, 73, 80, 85, 86],
       [79, 81, 77, 87, 74, 87, 86, 89],
       [89, 85, 80, 87, 84, 88, 89, 90]])

In [ ]:
np.sort(arr, axis = 1)

array([[58, 59, 60, 62, 64, 82, 86, 89],
       [52, 52, 64, 64, 66, 70, 76, 89],
       [51, 53, 65, 67, 67, 68, 74, 80],
       [50, 52, 59, 59, 64, 68, 71, 78],
       [52, 57, 65, 73, 73, 74, 78, 79],
       [52, 54, 58, 66, 73, 80, 85, 87],
       [61, 65, 68, 77, 82, 84, 85, 87],
       [57, 62, 63, 65, 72, 74, 85, 90],
       [52, 55, 62, 69, 70, 70, 81, 86],
       [60, 64, 68, 72, 84, 87, 88, 89]])

### Array Manipulation

- np.concatenate
- np.hstack
- np.vstack
- np.column_stack
- np.hsplit
- np.vsplit

In [ ]:
arr4 = np.random.randint(30, 54, size = (5,5))
arr5 = np.random.randint(30, 54, size = (5,5))

In [ ]:
np.concatenate((arr4, arr5), axis = 0)  #concatenate the arrays in vertical direction

array([[31, 43, 41, 32, 32],
       [30, 46, 45, 40, 33],
       [46, 32, 39, 33, 49],
       [47, 52, 41, 35, 34],
       [34, 47, 32, 45, 34],
       [33, 47, 51, 47, 35],
       [52, 36, 44, 46, 31],
       [39, 48, 37, 45, 30],
       [48, 30, 50, 42, 42],
       [33, 40, 32, 51, 31]])

In [ ]:
np.concatenate((arr4, arr5), axis = 1)  #concatenate the arrays in the horizontal direction

array([[31, 43, 41, 32, 32, 33, 47, 51, 47, 35],
       [30, 46, 45, 40, 33, 52, 36, 44, 46, 31],
       [46, 32, 39, 33, 49, 39, 48, 37, 45, 30],
       [47, 52, 41, 35, 34, 48, 30, 50, 42, 42],
       [34, 47, 32, 45, 34, 33, 40, 32, 51, 31]])

In [ ]:
np.vstack((arr4, arr5)) #similar to concatenate with axis = 0

array([[31, 43, 41, 32, 32],
       [30, 46, 45, 40, 33],
       [46, 32, 39, 33, 49],
       [47, 52, 41, 35, 34],
       [34, 47, 32, 45, 34],
       [33, 47, 51, 47, 35],
       [52, 36, 44, 46, 31],
       [39, 48, 37, 45, 30],
       [48, 30, 50, 42, 42],
       [33, 40, 32, 51, 31]])

In [ ]:
np.hstack((arr4, arr5)) #similar to concatenate with axis = 1

array([[31, 43, 41, 32, 32, 33, 47, 51, 47, 35],
       [30, 46, 45, 40, 33, 52, 36, 44, 46, 31],
       [46, 32, 39, 33, 49, 39, 48, 37, 45, 30],
       [47, 52, 41, 35, 34, 48, 30, 50, 42, 42],
       [34, 47, 32, 45, 34, 33, 40, 32, 51, 31]])

In [ ]:
arr_big = np.random.randint(40, 81, size = (12,10))

In [ ]:
arr_big

array([[75, 70, 49, 45, 47, 46, 77, 77, 47, 51],
       [76, 68, 45, 40, 67, 61, 63, 44, 57, 78],
       [42, 54, 76, 48, 74, 79, 63, 46, 54, 78],
       [74, 57, 46, 80, 64, 53, 49, 78, 77, 65],
       [79, 53, 65, 40, 57, 76, 60, 70, 78, 62],
       [71, 50, 67, 71, 45, 53, 58, 62, 43, 49],
       [52, 48, 55, 74, 53, 48, 80, 40, 49, 46],
       [55, 77, 60, 71, 80, 69, 65, 79, 66, 76],
       [60, 61, 52, 41, 72, 74, 44, 69, 68, 67],
       [44, 70, 46, 47, 62, 52, 68, 40, 76, 74],
       [57, 54, 80, 69, 61, 50, 57, 79, 78, 57],
       [61, 47, 59, 43, 63, 45, 70, 57, 80, 54]])

In [ ]:
arr11, arr12 = np.hsplit(arr_big, 2)

[array([[75, 70, 49, 45, 47],
        [76, 68, 45, 40, 67],
        [42, 54, 76, 48, 74],
        [74, 57, 46, 80, 64],
        [79, 53, 65, 40, 57],
        [71, 50, 67, 71, 45],
        [52, 48, 55, 74, 53],
        [55, 77, 60, 71, 80],
        [60, 61, 52, 41, 72],
        [44, 70, 46, 47, 62],
        [57, 54, 80, 69, 61],
        [61, 47, 59, 43, 63]]),
 array([[46, 77, 77, 47, 51],
        [61, 63, 44, 57, 78],
        [79, 63, 46, 54, 78],
        [53, 49, 78, 77, 65],
        [76, 60, 70, 78, 62],
        [53, 58, 62, 43, 49],
        [48, 80, 40, 49, 46],
        [69, 65, 79, 66, 76],
        [74, 44, 69, 68, 67],
        [52, 68, 40, 76, 74],
        [50, 57, 79, 78, 57],
        [45, 70, 57, 80, 54]])]

In [ ]:
np.vsplit(arr_big, 2)

[array([[75, 70, 49, 45, 47, 46, 77, 77, 47, 51],
        [76, 68, 45, 40, 67, 61, 63, 44, 57, 78],
        [42, 54, 76, 48, 74, 79, 63, 46, 54, 78],
        [74, 57, 46, 80, 64, 53, 49, 78, 77, 65],
        [79, 53, 65, 40, 57, 76, 60, 70, 78, 62],
        [71, 50, 67, 71, 45, 53, 58, 62, 43, 49]]),
 array([[52, 48, 55, 74, 53, 48, 80, 40, 49, 46],
        [55, 77, 60, 71, 80, 69, 65, 79, 66, 76],
        [60, 61, 52, 41, 72, 74, 44, 69, 68, 67],
        [44, 70, 46, 47, 62, 52, 68, 40, 76, 74],
        [57, 54, 80, 69, 61, 50, 57, 79, 78, 57],
        [61, 47, 59, 43, 63, 45, 70, 57, 80, 54]])]

### Array Inspection

In [ ]:
arr_big.shape #print the number of rows and columns in the array

(12, 10)

In [ ]:
arr_big.size  #prints the total number of elements present in the array

120

In [ ]:
arr_big.ndim  #tell us the dimension of the array

2

In [ ]:
arr_big.T #transpose of the array

array([[75, 76, 42, 74, 79, 71, 52, 55, 60, 44, 57, 61],
       [70, 68, 54, 57, 53, 50, 48, 77, 61, 70, 54, 47],
       [49, 45, 76, 46, 65, 67, 55, 60, 52, 46, 80, 59],
       [45, 40, 48, 80, 40, 71, 74, 71, 41, 47, 69, 43],
       [47, 67, 74, 64, 57, 45, 53, 80, 72, 62, 61, 63],
       [46, 61, 79, 53, 76, 53, 48, 69, 74, 52, 50, 45],
       [77, 63, 63, 49, 60, 58, 80, 65, 44, 68, 57, 70],
       [77, 44, 46, 78, 70, 62, 40, 79, 69, 40, 79, 57],
       [47, 57, 54, 77, 78, 43, 49, 66, 68, 76, 78, 80],
       [51, 78, 78, 65, 62, 49, 46, 76, 67, 74, 57, 54]])

In [ ]:
arr_big.ravel() #converts a higher dimension array into 1d array

array([75, 70, 49, 45, 47, 46, 77, 77, 47, 51, 76, 68, 45, 40, 67, 61, 63,
       44, 57, 78, 42, 54, 76, 48, 74, 79, 63, 46, 54, 78, 74, 57, 46, 80,
       64, 53, 49, 78, 77, 65, 79, 53, 65, 40, 57, 76, 60, 70, 78, 62, 71,
       50, 67, 71, 45, 53, 58, 62, 43, 49, 52, 48, 55, 74, 53, 48, 80, 40,
       49, 46, 55, 77, 60, 71, 80, 69, 65, 79, 66, 76, 60, 61, 52, 41, 72,
       74, 44, 69, 68, 67, 44, 70, 46, 47, 62, 52, 68, 40, 76, 74, 57, 54,
       80, 69, 61, 50, 57, 79, 78, 57, 61, 47, 59, 43, 63, 45, 70, 57, 80,
       54])

In [ ]:
arr_big

array([[75, 70, 49, 45, 47, 46, 77, 77, 47, 51],
       [76, 68, 45, 40, 67, 61, 63, 44, 57, 78],
       [42, 54, 76, 48, 74, 79, 63, 46, 54, 78],
       [74, 57, 46, 80, 64, 53, 49, 78, 77, 65],
       [79, 53, 65, 40, 57, 76, 60, 70, 78, 62],
       [71, 50, 67, 71, 45, 53, 58, 62, 43, 49],
       [52, 48, 55, 74, 53, 48, 80, 40, 49, 46],
       [55, 77, 60, 71, 80, 69, 65, 79, 66, 76],
       [60, 61, 52, 41, 72, 74, 44, 69, 68, 67],
       [44, 70, 46, 47, 62, 52, 68, 40, 76, 74],
       [57, 54, 80, 69, 61, 50, 57, 79, 78, 57],
       [61, 47, 59, 43, 63, 45, 70, 57, 80, 54]])